removed zeroes from flyleaf titles
UCLALibrary/sinai_metadata pull request #214
Opened 2024-03-27 23:06 UTC by ngoziharrison

2024-03-27 23:39 UTC, kirschbombe requested changes
The script is removing rows and touching CSVs that it shouldn't. You'll need to revert these changes and do some further script testing.

2024-03-28 17:58 UTC, ngoziharrison commented
@wlpotter Just updated the branch to fix the issues removing rows and keeping the spaces. Take a look and let me know what you think

2024-03-28 18:28 UTC, wlpotter reviewed
I've reviewed the csvs that were changed from del1 and it looks like the script is working.

2024-03-30 18:50 UTC, kirschbombe approved these changes

2024-03-30 18:50 UTC, merged